language: node_js
node_js:
- '8'
install:
- npm i
before_script:
- npm test
script:
- npm run build
before_deploy:
- npm i -g makeshift && makeshift -s $NPM_USER -r https://registry.npmjs.org
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    branch: master
