language: node_js
node_js:
- '8'
before_install:
- npm i -g makeshift && makeshift -s @mnorrish -r https://registry.npmjs.org
install:
- npm i
before_script:
- npm test
script:
- npm run build
deploy:
  provider: npm
  email: matt@mnorrish.co.nz
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    branch: master
